# Generated by Django 4.2.2 on 2023-06-22 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_img', models.ImageField(blank=True, null=True, upload_to='MediaFiles/')),
                ('answer', models.TextField()),
                ('answer_img', models.ImageField(blank=True, null=True, upload_to='MediaFiles/')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50)),
                ('length', models.CharField(choices=[('one Word', 'One Word'), ('Very short', 'Very Short'), ('Short', 'Short'), ('Long', 'Long'), ('Very long', 'Very Long')], max_length=100)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
                ('Chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chapter')),
            ],
        ),
    ]
