# Generated by Django 4.2.2 on 2023-06-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_truefalse_mcq_fillup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='truefalse',
            name='class_name',
        ),
    ]
