# Generated by Django 4.2.2 on 2023-06-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=300)),
                ('class_name', models.CharField(choices=[('class 6', 'class 6'), ('class 7', 'class 7'), ('class 8', 'class 8'), ('class 9', 'class 9'), ('class 10', 'class 10'), ('class 11', 'class 11'), ('class 12', 'class 12')], max_length=100)),
                ('subject_name', models.CharField(choices=[('Science', 'Science'), ('Maths', 'Maths'), ('Hindi', 'Hindi'), ('English', 'English'), ('Social Science', 'Social Science'), ('Sanskrit', 'Sanskrit')], max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('duration', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('instructions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
