# Generated by Django 4.2.2 on 2023-07-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolCore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperdetail',
            name='class_name',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='paperdetail',
            name='subject_name',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
