# Generated by Django 4.2.2 on 2023-07-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToolCore', '0003_userlogin_toollogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toollogin',
            old_name='paper_credentials',
            new_name='paper_credential',
        ),
    ]
