# Generated by Django 4.2.2 on 2023-07-19 05:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ToolCore', '0004_rename_paper_credentials_toollogin_paper_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('paper_html', models.TextField()),
                ('solution_html', models.TextField()),
                ('saved_paper', models.FileField(upload_to='saved_papers/')),
                ('saved_solution', models.FileField(upload_to='saved_solutions/')),
                ('tool_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToolCore.toollogin')),
            ],
        ),
    ]
