# Generated by Django 4.2.2 on 2023-07-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolCore', '0006_paper_class_name_paper_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toollogin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='toollogin',
            name='tool_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
