# Generated by Django 4.2.2 on 2023-07-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolCore', '0007_alter_toollogin_email_alter_toollogin_tool_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='email_token',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
