# Generated by Django 4.2.2 on 2023-07-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolCore', '0008_userlogin_email_token_userlogin_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='email_token',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
